### ISSUE TITLE
Excel / $key must be a string or an array

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#152]
This is show when selecting the "excel" format on "Special:Ask":
```
Exception encountered, of type "InvalidArgumentException"
[0e75b58d] /w/index.php?title=Special:Ask&showformatoptions=excel&params[title]=Special%3AAsk&params[offset]=&params[limit]= InvalidArgumentException from line 240 of /.../w/includes/Message.php: $key must be a string or an array
Backtrace:
#0 /.../w/includes/GlobalFunctions.php(1422): Message->__construct(NULL, array)
#1 [internal function]: wfMessage(NULL)
#2 /.../w/includes/context/RequestContext.php(436): call_user_func_array(string, array)
#3 [internal function]: RequestContext->msg(NULL)
#4 /.../w/includes/specialpage/SpecialPage.php(608): call_user_func_array(array, array)
#5 /.../w/extensions/SemanticMediaWiki/includes/specials/SMW_QuerySpecialPage.php(63): SpecialPage->msg(NULL)
#6 /.../w/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(60): SMWQuerySpecialPage->showFormatOptions(string, array)
#7 /.../w/includes/specialpage/SpecialPage.php(384): SMWAskPage->execute(NULL)
#8 /.../w/includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run(NULL)
#9 /.../w/includes/MediaWiki.php(263): SpecialPageFactory::executePath(Title, RequestContext)
#10 /.../w/includes/MediaWiki.php(634): MediaWiki->performRequest()
#11 /.../w/includes/MediaWiki.php(482): MediaWiki->main()
#12 /.../w/index.php(41): MediaWiki->run()
#13 {main}
```
- MW 1.25.2
- SMW 2.4-alpha 
- SRF 2.3
- PHP 5.4.45

**Comment by mwjames** [comment]
I have no idea why `$definition->getMessage()` returns null but in case it is `null` we just move on [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/6b95a6b2fd7f9ff26a8136c3ff4ab2d3f030ebab

**Comment by kghbln** [comment]
That was fast. Thanks a bunch!

**Comment by kghbln** [comment]
Follow up https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/3c57311b92fc66cabfcafd504b0bb94a7a0ccc41
