### ISSUE TITLE
Filtered format: "SRF\Filtered\Filtered::setParser() must be an instance of Parser..."

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#305]
### Setup

- MW version: 1.27
- DB (MySQL etc.): Maria
- PHP version: 7.0
- SMW version: 2.5.4
- SRF version: 2.5.2
- Browsers and versions (if applicable):

### Issue

```
Exception encountered, of type "TypeError"
[0b30792a289956848009d2c6] /w/index.php?title=Special%3AAsk&q=%5B%5BCategory%3AAsk+syntax%5D%5D+%5B%5BHas+component%3A%3ASemantic+MediaWiki%5D%5D&po=&eq=yes&p%5Bformat%5D=filtered&sort_num=&order_num=ASC&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bviews%5D=&p%5Bfilter+position%5D=top&p%5Blist+view+type%5D=list&p%5Blist+view+template%5D=&p%5Blist+view+introtemplate%5D=&p%5Blist+view+outrotemplate%5D=&p%5Bcalendar+view+start%5D=&p%5Bcalendar+view+end%5D=&p%5Bcalendar+view+title%5D=&p%5Bcalendar+view+title+template%5D=&p%5Btable+view+class%5D=wikitable+sortable&p%5Bmap+view+marker+position+property%5D=&eq=yes TypeError from line 99 of /var/www/html/02310/w/extensions/SemanticResultFormats/formats/filtered/src/Filtered.php: Argument 1 passed to SRF\Filtered\Filtered::setParser() must be an instance of Parser, instance of StubObject given, called in /var/www/html/02310/w/extensions/SemanticResultFormats/formats/filtered/src/Filtered.php on line 90
Backtrace:
#0 /var/www/html/02310/w/extensions/SemanticResultFormats/formats/filtered/src/Filtered.php(90): SRF\Filtered\Filtered->setParser(StubObject)
#1 /var/www/html/02310/w/extensions/SemanticResultFormats/formats/filtered/src/Filtered.php(367): SRF\Filtered\Filtered->getParser()
#2 /var/www/html/02310/w/extensions/SemanticResultFormats/formats/filtered/src/Filtered.php(305): SRF\Filtered\Filtered->addConfigToOutput(string, array)
#3 /var/www/html/02310/w/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php(261): SRF\Filtered\Filtered->getResultText(SMWQueryResult, integer)
#4 /var/www/html/02310/w/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php(226): SMW\ResultPrinter->buildResult(SMWQueryResult)
#5 /var/www/html/02310/w/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(372): SMW\ResultPrinter->getResult(SMWQueryResult, array, integer)
#6 /var/www/html/02310/w/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(103): SMWAskPage->makeHTMLResult()
#7 /var/www/html/02310/w/includes/specialpage/SpecialPage.php(479): SMWAskPage->execute(NULL)
#8 /var/www/html/02310/w/includes/specialpage/SpecialPageFactory.php(577): SpecialPage->run(NULL)
#9 /var/www/html/02310/w/includes/MediaWiki.php(282): SpecialPageFactory::executePath(Title, RequestContext)
#10 /var/www/html/02310/w/includes/MediaWiki.php(735): MediaWiki->performRequest()
#11 /var/www/html/02310/w/includes/MediaWiki.php(509): MediaWiki->main()
#12 /var/www/html/02310/w/index.php(43): MediaWiki->run()
#13 {main}
```

### Steps to reproduce:

* https://www.semantic-mediawiki.org/w/index.php?title=Special%3AAsk&q=%5B%5BCategory%3AAsk+syntax%5D%5D+%5B%5BHas+component%3A%3ASemantic+MediaWiki%5D%5D&po=&eq=yes&p%5Bformat%5D=filtered&sort_num=&order_num=ASC&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bviews%5D=&p%5Bfilter+position%5D=top&p%5Blist+view+type%5D=list&p%5Blist+view+template%5D=&p%5Blist+view+introtemplate%5D=&p%5Blist+view+outrotemplate%5D=&p%5Bcalendar+view+start%5D=&p%5Bcalendar+view+end%5D=&p%5Bcalendar+view+title%5D=&p%5Bcalendar+view+title+template%5D=&p%5Btable+view+class%5D=wikitable+sortable&p%5Bmap+view+marker+position+property%5D=&eq=yes

**Comment by s7eph4n** [comment]
I guess the fix will just be removing the type hint from the function definition.
