### ISSUE TITLE
DataTables with reference/fields properties crash if a field has correspondence units

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticResultFormats#437]
### Setup
- Core & extensions download & install date: Sept 2018
- MW version: 1.3.10
- DB (MySQL etc.): mysql
- PHP version: 7.2.10
- SMW version: 2.5.8
- SRF version: 2.5.6
- Browsers and versions (if applicable): Chrome latest

### Issue

When semantically-searching pages that contain a ["reference" property](Help:Reference_and_provenance_data), and if that `Ref prop` has a `[[Has type:Quantity]]` `Field prop` which has units specified with `[[Property:Corresponds to]]`, the search fails at the API HTTP call, and you get this this stack printed inside the `Semantic:Ask` page:

```
[2adc3b5803483af8961ddae0] /wiki/index.php?title=Special%3AAsk&q=%5B%5BCategory%3AEntities%5D%5D%5B%5BFD009%5D%5D&po=%3FRef prop.Field prop%3DLLL%0D%0A&eq=yes&p%5Bformat%5D=datatables&sort_num=&order_num=ASC&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Btheme%5D=bootstrap&eq=yes 
TypeError from line 162 of /var/lib/wiki/extensions/SemanticMediaWiki/src/DataValueFactory.php: 
Argument 2 passed to SMW\DataValueFactory::newDataValueByItem() must be an instance of SMW\DIProperty or null, 
instance of SMWDIBlob given, called in /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php on line 119

Backtrace:

#0 /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(119): SMW\DataValueFactory->newDataValueByItem(SMWDINumber, SMWDIBlob)
#1 /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(185): SMW\Serializers\QueryResultSerializer::getSerialization(SMWDINumber, SMW\Query\PrintRequest)
#2 /var/lib/wiki/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(45): SMW\Serializers\QueryResultSerializer::getSerializedQueryResult(SMWQueryResult)
#3 /var/lib/wiki/extensions/SemanticMediaWiki/includes/storage/SMW_QueryResult.php(319): SMW\Serializers\QueryResultSerializer->serialize(SMWQueryResult)
#4 /var/lib/wiki/extensions/SemanticMediaWiki/includes/storage/SMW_QueryResult.php(346): SMWQueryResult->serializeToArray()
#5 /var/lib/wiki/extensions/SemanticMediaWiki/includes/queryprinters/RawResultPrinter.php(123): SMWQueryResult->toArray()
#6 /var/lib/wiki/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php(261): SMW\RawResultPrinter->getResultText(SMWQueryResult, integer)
#7 /var/lib/wiki/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php(226): SMW\ResultPrinter->buildResult(SMWQueryResult)
#8 /var/lib/wiki/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(372): SMW\ResultPrinter->getResult(SMWQueryResult, array, integer)
#9 /var/lib/wiki/extensions/SemanticMediaWiki/includes/specials/SMW_SpecialAsk.php(103): SMWAskPage->makeHTMLResult()
#10 /var/lib/wiki/includes/specialpage/SpecialPage.php(522): SMWAskPage->execute(NULL)
#11 /var/lib/wiki/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#12 /var/lib/wiki/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#13 /var/lib/wiki/includes/MediaWiki.php(861): MediaWiki->performRequest()
#14 /var/lib/wiki/includes/MediaWiki.php(524): MediaWiki->main()
#15 /var/lib/wiki/index.php(42): MediaWiki->run()
#16 {main}
```

~~But the real strange thing is that in the pre-production wiki it passes!!~~
Any idea how to help debug it?
### Note 1: 
When a reference property does not have "units", search works without crashes, like that:
- if the parent 'ref" property asked, it prints `[object]` (while eg `broadtable` would include the rest fields in a citation-like superscript)
- if a field-prop asked with `?Ref prop.Field prop=label`, it is displayed as a normal column.

#### Note 2: 
The manual refers to a known limitation about `[[Property:Display units]]` special property.  So maybe it should include also the `[[Property:Corresponds to]]` property as well.

### Steps to reproduce
By creating the pages below, the pre-production did ~~NOT~~ fail. 
But i cannot test the exact same on our production now, but a similar setup of properties fail with `DataTables`:

#### `Property:Ref prop`:
```mediawiki
* [[Has type::Reference]]
* [[Has fields::Field prop;other prop]]
```
#### `Property:Field prop`:
```mediawiki
[[Has type::Quantity]]
[[Corresponds to::1 km]]
```
#### `Foo page`:
```mediawiki
[[Good prop::ok]]
[[Ref prop::123;unsearchable in datatable]]
```
#### #Ask queries
(edit: Had forgotten to compete the queries)
```wikitext
{{#ask: [[Ref2 prop::;~B*]]
 |?Ref prop
 |?Ref prop.field prop=Field prop
 |format=DataTables
 |link=all
 |headers=show
 |searchlabel=... further results
 |class=sortable wikitable smwtable
}}

{{#ask: [[Base1 prop::;~B*]]
 |?Ref2 prop
 |?Ref2 prop.field prop=Field prop
 |?Ref2 prop.other prop=Other prop
 |format=DataTables
 |link=all
 |headers=show
 |searchlabel=... further results
 |class=sortable wikitable smwtable
}}

```

**Comment by ankostis** [comment]
Nope, it fails deterministically, also in the other wiki.
Just updated the sample queries failing.

**Comment by kghbln** [comment]
Thanks a lot for reporting this issue in such detail. I suspect that this use case was not considered when the reference datatype was introduced. Moreover the datatables format has not seen any big maintenance since it was introduced.
