### ISSUE TITLE
Gallery format: Error from line 275 in "Gallery.php": Call to private method SMWWikiPageValue::getTitle() from context 'SRF\Gallery'

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#494]
### Setup

- MediaWiki | 1.33.0-rc.0 (f938437)22:28, 7. Jun. 2019
- PHP | 7.2.19-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.40-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.1.0-alpha (de582d4) 20:36, 10. Jun. 2019
- Semantic Result Formats | 3.1.0-alpha (acb7d1b) 16:51, 27. Mai 2019

### Issue
This came in from sandbox via runJobs.php by cron:
```
[eb1b0f1440c96d3ebaa0bd87] [no req]   Error from line 275 of /../w/extensions/SemanticResultFormats/formats/gallery/Gallery.php: Call to private method SMWWikiPageValue::getTitle() from context 'SRF\Gallery'
```

### Backtrace
```
#0 /../w/extensions/SemanticResultFormats/formats/gallery/Gallery.php(151): SRF\Gallery->addImagePages(SMW\Query\QueryResult, TraditionalImageGallery)
#1 /../w/extensions/SemanticResultFormats/formats/gallery/Gallery.php(55): SRF\Gallery->getResultText(SMW\Query\QueryResult, integer)
#2 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(307): SRF\Gallery->buildResult(SMW\Query\QueryResult)
#3 /../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(398): SMW\Query\ResultPrinters\ResultPrinter->getResult(SMW\Query\QueryResult, array, integer)
#4 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(364): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#5 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(197): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#6 /../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#7 /../w/includes/parser/Parser.php(3528): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string)
#8 /../w/includes/parser/Parser.php(3235): Parser->callParserFunction(PPFrame_DOM, string, array)
#9 /../w/includes/parser/Preprocessor_DOM.php(1285): Parser->braceSubstitution(array, PPFrame_DOM)
#10 /../w/includes/parser/Parser.php(3049): PPFrame_DOM->expand(DOMElement, integer)
#11 /../w/includes/parser/Parser.php(1359): Parser->replaceVariables(string)
#12 /../w/includes/parser/Parser.php(491): Parser->internalParse(string)
#13 /../w/includes/content/WikitextContent.php(369): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#14 /../w/includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#15 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(186): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#16 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(145): SMW\ContentParser->fetchFromContent()
#17 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(197): SMW\ContentParser->parse()
#18 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#19 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#20 /../w/includes/jobqueue/JobRunner.php(290): SMW\MediaWiki\Jobs\UpdateJob->run()
#21 /../w/includes/jobqueue/JobRunner.php(192): JobRunner->executeJob(SMW\MediaWiki\Jobs\UpdateJob, Wikimedia\Rdbms\LBFactorySimple, BufferingStatsdDataFactory, integer)
#22 /../w/maintenance/runJobs.php(89): JobRunner->run(array)
#23 /../w/maintenance/doMaintenance.php(96): RunJobs->execute()
#24 /../w/maintenance/runJobs.php(126): require_once(string)
#25 {main}
```

**Comment by kghbln** [comment]
@JeroenDeDauw FYI

**Comment by kghbln** [comment]
Great, now I realize we already have #493
