### ISSUE TITLE
[Valuerank] "SRF_ValueRank.php": Call to a member function getText() on null

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticResultFormats#602]
### Setup

- MW version: 1.34.0
- DB: Percona
- PHP version: 7.3.19
- SMW version: 3.1.6 
- SRF version: 3.2.0-alpha (42927fc)
- Browsers and versions (if applicable): FF

**Stacktrace** 

```
2020-07-17 17:38:37 unknown! wiki-wiki1: [7df6fc6279aeed2bc4e661e9] [no req]   Error from line 95 of .../extensions/SemanticResultFormats/formats/valuerank/SRF_ValueRank.php: Call to a member function getText() on null
#0 .../extensions/SemanticResultFormats/formats/valuerank/SRF_ValueRank.php(59): SRFValueRank->getResultValues(SMW\Query\QueryResult, integer)
#1 .../extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(347): SRFValueRank->getResultText(SMW\Query\QueryResult, integer)
#2 .../extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(312): SMW\Query\ResultPrinters\ResultPrinter->buildResult(SMW\Query\QueryResult)
#3 .../extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(348): SMW\Query\ResultPrinters\ResultPrinter->getResult(SMW\Query\QueryResult, array, integer)
#4 .../extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(364): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#5 .../extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(196): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#6 .../extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#7 .../includes/parser/Parser.php(3816): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string)
#8 .../includes/parser/Parser.php(3519): Parser->callParserFunction(PPFrame_Hash, string, array)
#9 .../includes/parser/PPFrame_Hash.php(254): Parser->braceSubstitution(array, PPFrame_Hash)
#10 .../includes/parser/Parser.php(3330): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#11 .../includes/parser/Parser.php(1489): Parser->replaceVariables(string)
#12 .../includes/parser/Parser.php(593): Parser->internalParse(string)
#13 .../includes/content/WikitextContent.php(368): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#14 .../includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#15 .../includes/Revision/RenderedRevision.php(264): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#16 .../includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#17 .../includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#18 .../includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#19 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#20 .../includes/Revision/RenderedRevision.php(198): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#21 .../includes/jobqueue/jobs/RefreshLinksJob.php(259): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput(array)
#22 .../includes/jobqueue/jobs/RefreshLinksJob.php(179): RefreshLinksJob->getParserOutput(MediaWiki\Revision\RevisionRenderer, ParserCache, WikiPage, BufferingStatsdDataFactory)
#23 .../includes/jobqueue/jobs/RefreshLinksJob.php(126): RefreshLinksJob->runForTitle(Title)
#24 .../includes/jobqueue/JobRunner.php(299): RefreshLinksJob->run()
#25 .../includes/jobqueue/JobRunner.php(192): JobRunner->executeJob(RefreshLinksJob, Wikimedia\Rdbms\LBFactorySimple, BufferingStatsdDataFactory, integer)
#26 .../maintenance/runJobs.php(92): JobRunner->run(array)
#27 .../maintenance/doMaintenance.php(99): RunJobs->execute()
#28 .../maintenance/runJobs.php(129): require_once(string)
#29 {main}
```
`unknown!` indicates that this is from the cli when SERVER_NAME is not set.

**Comment by kghbln** [comment]
Thanks for reporting.
