### ISSUE TITLE
[spreadsheet] Invalid numeric value for datatype Numeric

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#679]
### Setup

- MediaWiki | 1.35.4 (e78db82)2021-10-10T21:41:58
- PHP | 7.4.3 (apache2handler)
- MariaDB | 10.3.31-MariaDB-0ubuntu0.20.04.
- Semantic MediaWiki | 3.2.3
- Semantic Result Formats | 3.2.0
- phpoffice/phpspreadsheet | 1.19.0

### Issue
This is the query causing the issue:
```
{{#ask:
 [[Concept:Persoon in]]
 |?Geboortedatum
 |?Geboortedatum#-F[d]=geboortedag
 |?Geboortedatum#-F[m]=geboortemaand
 |?Overlijdensdatum
 |?Overlijdensdatum#-F[d]=Overlijdensdag
 |?Overlijdensdatum#-F[m]=Overlijdensmaand
 |format=spreadsheet
 |fileformat=xlsx
 |filename=Export_data_personen_theaterkalender
 |searchlabel=Export (xlsx)
 |limit=10
}}
```
When clicking to export the results ...
```
2021-11-03 15:25:48 db: [9d00cbe9bb8d1ea81667dc7d] /wiki/Speciaal:Vragen/-5B-5BConcept:Persoon-5D/-3FGeboortedatum-23-2DF-5Bd-5D/-3FGeboortedatum-23-2DF-5Bm-5D/-3FOverlijdensdatum/-3FOverlijdensdatum-23-2DF-5Bd-5D/-3FOverlijdensdatum-23-2DF-5Bm-5D/mainlabel%3D/limit%3D10/offset%3D0/format%3Dspreadsheet/searchlabel%3DExport-20(xlsx)/filename%3DExport-5Fdata-5Fpersonen-5Ftheaterkalender/fileformat%3Dxlsx   PhpOffice\PhpSpreadsheet\Exception from line 215 of /../w/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php: Invalid numeric value for datatype Numeric
```
... the server issues an error 500 with the following backtrace. I personally think it may the the number formatting which is part of the query.

### Backtrace
```
#0 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(414): PhpOffice\PhpSpreadsheet\Cell\Cell->setValueExplicit()
#1 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(352): SRF\SpreadsheetPrinter->setTimeDataValue()
#2 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(325): SRF\SpreadsheetPrinter->populateCellAccordingToType()
#3 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(291): SRF\SpreadsheetPrinter->populateCell()
#4 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(241): SRF\SpreadsheetPrinter->populateRow()
#5 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(164): SRF\SpreadsheetPrinter->populateWorksheet()
#6 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(145): SRF\SpreadsheetPrinter->getResultFileContents()
#7 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(341): SRF\SpreadsheetPrinter->getResultText()
#8 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(306): SMW\Query\ResultPrinters\ResultPrinter->buildResult()
#9 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/FileExportPrinter.php(106): SMW\Query\ResultPrinters\ResultPrinter->getResult()
#10 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/FileExportPrinter.php(53): SMW\Query\ResultPrinters\FileExportPrinter->getFileResult()
#11 /../w/extensions/SemanticResultFormats/formats/spreadsheet/SpreadsheetPrinter.php(94): SMW\Query\ResultPrinters\FileExportPrinter->outputAsFile()
#12 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(338): SRF\SpreadsheetPrinter->outputAsFile()
#13 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(170): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#14 /../w/includes/specialpage/SpecialPage.php(600): SMW\MediaWiki\Specials\SpecialAsk->execute()
#15 /../w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#16 /../w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#17 /../w/includes/MediaWiki.php(940): MediaWiki->performRequest()
#18 /../w/includes/MediaWiki.php(543): MediaWiki->main()
#19 /../w/index.php(53): MediaWiki->run()
#20 /../w/index.php(46): wfIndexMain()
#21 {main}
```

**Comment by kghbln** [comment]
> I personally think it may the the number formatting which is part of the query.

Just checked. Removing the number formatting does not avoid the issue.
```
{{#ask:
 [[Concept:Persoon]]
 |?Geboortedatum
 |?Geboortedatum=geboortedag
 |?Geboortedatum=geboortemaand
 |?Overlijdensdatum
 |?Overlijdensdatum=Overlijdensdag
 |?Overlijdensdatum=Overlijdensmaand
 |format=spreadsheet
 |fileformat=xlsx
 |filename=Export_data_personen_theaterkalender
 |searchlabel=Export (xlsx)
 |limit=10
}}
```

**Comment by krabina** [comment]
Is this still happening?

**Comment by gesinn-it-gea** [comment]
I can not confirm this issue.

Tested on:
- MediaWiki 1.35.11
- MySQL 5.7.44
- PHP 7.4.33 (apache2handler)
- SMW 4.1.2
- SRF 4.0.2
- phpoffice/phpspreadsheet 1.29.0

with:
```
{{#ask:[[Category:Person]]
 |?Given Name
 |?Family Name
 |?Date Of Birth
 |format=spreadsheet
 |fileformat=xlsx
 |filename=Export_data_personen_theaterkalender
 |searchlabel=Export (xlsx)
}}
```
