### ISSUE TITLE
Class 'SMW\ResultPrinter' not found

### ISSUE THREAD

**Issue by malberts** [SemanticMediaWiki/SemanticResultFormats#694]
### Setup

- MW version: 1.37 (and 1.36)
- DB (MySQL etc.): MariaDB 10.6.4
- PHP version: 7.4.27
- SMW version: 4.0.0-rc1 / latest master (https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/afe662c13747ba4339ef2a99fadf9761f01e7a37)
- SRF version: latest master (https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/598c269c621ca540db5a8d3d90ffda6b8f0da75f)
- Browsers and versions (if applicable): n/a

### Issue

With SMW and SRF enabled, this bug is immediately reproducable.

**Steps to reproduce**

Go to page: Special:Ask

**Expected result:**
No exception should be thrown.

**Observed result:**
An exception is thrown.

**Stacktrace** 

```
[03065fba20d64cd4b5d16580] /Special:Ask Error: Class 'SMW\ResultPrinter' not found

Backtrace:

from /var/www/html/extensions/SemanticResultFormats/formats/calendar/EventCalendar.php(28)
#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile(string)
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass(string)
#3 /var/www/html/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(405): spl_autoload_call(string)
#4 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/FormatListWidget.php(100): SMWQueryProcessor::getResultPrinter(string, integer)
#5 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/FormatListWidget.php(65): SMW\MediaWiki\Specials\Ask\FormatListWidget::formatList(string, string, string, string, string)
#6 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/ParametersWidget.php(121): SMW\MediaWiki\Specials\Ask\FormatListWidget::selectList(Title, array)
#7 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(370): SMW\MediaWiki\Specials\Ask\ParametersWidget::fieldset(Title, array)
#8 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(201): SMW\MediaWiki\Specials\Ask\HtmlForm->editElements(SMW\Utils\UrlArgs)
#9 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(144): SMW\MediaWiki\Specials\Ask\HtmlForm->buildHTML(SMW\Utils\UrlArgs, NULL, array)
#10 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(399): SMW\MediaWiki\Specials\Ask\HtmlForm->getForm(SMW\Utils\UrlArgs, NULL, array)
#11 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(170): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#12 /var/www/html/includes/specialpage/SpecialPage.php(647): SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#13 /var/www/html/includes/specialpage/SpecialPageFactory.php(1366): SpecialPage->run(NULL)
#14 /var/www/html/includes/MediaWiki.php(314): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#15 /var/www/html/includes/MediaWiki.php(930): MediaWiki->performRequest()
#16 /var/www/html/includes/MediaWiki.php(564): MediaWiki->main()
#17 /var/www/html/index.php(53): MediaWiki->run()
#18 /var/www/html/index.php(46): wfIndexMain()
#19 {main}
```

**Comment by malberts** [comment]
SMW bug: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5173

**Comment by hexmode** [comment]
I think this is fixed now.  Please reopen if you continue to have problems.
